# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test1.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(Dialog)
        self.centralwidget.setObjectName("centralwidget")
        self.buttonBox = QtWidgets.QDialogButtonBox(self.centralwidget)
        self.buttonBox.setGeometry(QtCore.QRect(8, 570, 782, 26))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.lcdNumPostOst = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumPostOst.setGeometry(QtCore.QRect(740, 60, 80, 40))
        self.lcdNumPostOst.setObjectName("lcdNumPostOst")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setEnabled(True)
        self.label_2.setGeometry(QtCore.QRect(640, 70, 80, 20))
        self.label_2.setMinimumSize(QtCore.QSize(80, 20))
        self.label_2.setMaximumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(8, 114, 696, 440))
        self.tabWidget.setObjectName("tabWidget")
        self.Post = QtWidgets.QWidget()
        self.Post.setObjectName("Post")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.Post)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tablePostupl = QtWidgets.QTableWidget(self.Post)
        self.tablePostupl.setObjectName("tablePostupl")
        self.tablePostupl.setColumnCount(0)
        self.tablePostupl.setRowCount(0)
        self.gridLayout_2.addWidget(self.tablePostupl, 0, 1, 1, 1)
        self.tabWidget.addTab(self.Post, "")
        self.rashod = QtWidgets.QWidget()
        self.rashod.setObjectName("rashod")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.rashod)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tableRashod = QtWidgets.QTableView(self.rashod)
        self.tableRashod.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tableRashod.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.tableRashod.setAcceptDrops(False)
        self.tableRashod.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.tableRashod.setGridStyle(QtCore.Qt.SolidLine)
        self.tableRashod.setObjectName("tableRashod")
        self.gridLayout_3.addWidget(self.tableRashod, 0, 0, 1, 1)
        self.tabWidget.addTab(self.rashod, "")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(640, 20, 80, 20))
        self.label.setMaximumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lcdNumPost = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumPost.setGeometry(QtCore.QRect(740, 10, 80, 40))
        self.lcdNumPost.setObjectName("lcdNumPost")
        self.toolButton = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton.setGeometry(QtCore.QRect(730, 180, 26, 24))
        self.toolButton.setObjectName("toolButton")
        self.bottonAdd = QtWidgets.QPushButton(self.centralwidget)
        self.bottonAdd.setGeometry(QtCore.QRect(720, 270, 41, 25))
        self.bottonAdd.setObjectName("bottonAdd")
        self.bottonEdit = QtWidgets.QPushButton(self.centralwidget)
        self.bottonEdit.setGeometry(QtCore.QRect(720, 300, 41, 25))
        self.bottonEdit.setObjectName("bottonEdit")
        Dialog.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Dialog)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 824, 22))
        self.menubar.setObjectName("menubar")
        Dialog.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Dialog)
        self.statusbar.setObjectName("statusbar")
        Dialog.setStatusBar(self.statusbar)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Домашняя бухгалтерия"))
        self.label_2.setText(_translate("Dialog", "Остаток"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Post), _translate("Dialog", "Поступления"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.rashod), _translate("Dialog", "Расход"))
        self.label.setText(_translate("Dialog", "Остаток"))
        self.toolButton.setText(_translate("Dialog", "..."))
        self.bottonAdd.setText(_translate("Dialog", "add"))
        self.bottonEdit.setText(_translate("Dialog", "edit"))
